### ISSUE TITLE
setCoreVersion没有正常工作

### ISSUE THREAD

**Issue by Crystal0404** [Fallen-Breath/fabric-mod-template#3]
### Bug description

setCoreVersion没有正常工作

### Steps to reproduce

1. 创建一个如图示例
<img width="1279" alt="1" src="https://github.com/user-attachments/assets/2d6d683b-cd07-4fc2-bdd1-1f8b6bec800c">

2. 于控制台中使用指令 `./gradlew :1.21.1:setCoreVersion`

### Expected behavior

下图红圈位置的代码正确处理

### Actual behavior

<img width="1280" alt="2" src="https://github.com/user-attachments/assets/383644e6-2009-45f8-b076-b8eeffb926bd">

画红圈的地方没正确处理, 但`mainProject`中的值被正确处理

### Minecraft version

无

### TemplateMod version

无

### Other information

这个bug应该来自 https://github.com/Fallen-Breath/preprocessor 中的错误

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
> 创建一个如图示例

“如图所示”并非是一个对可复现环境的描述方式。请使用诸如“使用 xxx commit 处的代码，执行 yyy 操作”等的清晰客观可复现操作

比如，使用 https://github.com/Fallen-Breath/fabric-mod-template/commit/ad51f9a255b042ac99830770f025fec71756ee01 处的环境，执行 `1.16.5:setCoreVersion` 任务，会发现 `me/fallenbreath/template_mod/mixins/MinecraftServerMixin.java` 处的文件未发生变化

> 这个bug应该来自 https://github.com/Fallen-Breath/preprocessor 中的错误

[上游](https://github.com/ReplayMod/preprocessor) 的问题，与我的 fork 无关。该问题使用上游的 [7de7ac9dc2](https://github.com/ReplayMod/preprocessor/commit/7de7ac9dc232ac554ccd0ac99167652b9ac4e0a9) 一样可以复现
